version: '3'

services:
  rust-centos7:
    build:
      context: docker
      dockerfile: Dockerfile.centos7
    environment:
    - VERSION
    volumes:
    - ../..:/workspace
    command: /workspace/packaging/rpm/build.sh ${UID} ${GID}
